-- PlateTrack seed data — run after 01_main.sql

-- ── STRENGTH STANDARDS ────────────────────────────────────────
INSERT INTO public.strength_standards_cache (sex, exercise_key, level, bw_multiplier) VALUES
('m','squat',0,0.50),('m','squat',1,0.75),('m','squat',2,1.25),('m','squat',3,1.75),('m','squat',4,2.25),
('m','bench',0,0.50),('m','bench',1,0.65),('m','bench',2,1.00),('m','bench',3,1.40),('m','bench',4,1.75),
('m','deadlift',0,0.75),('m','deadlift',1,1.00),('m','deadlift',2,1.50),('m','deadlift',3,2.00),('m','deadlift',4,2.50),
('m','ohp',0,0.30),('m','ohp',1,0.40),('m','ohp',2,0.65),('m','ohp',3,0.85),('m','ohp',4,1.10),
('f','squat',0,0.30),('f','squat',1,0.50),('f','squat',2,0.80),('f','squat',3,1.15),('f','squat',4,1.50),
('f','bench',0,0.25),('f','bench',1,0.35),('f','bench',2,0.55),('f','bench',3,0.80),('f','bench',4,1.00),
('f','deadlift',0,0.40),('f','deadlift',1,0.65),('f','deadlift',2,1.00),('f','deadlift',3,1.40),('f','deadlift',4,1.75),
('f','ohp',0,0.15),('f','ohp',1,0.25),('f','ohp',2,0.40),('f','ohp',3,0.55),('f','ohp',4,0.75)
ON CONFLICT DO NOTHING;

-- ── ACHIEVEMENTS ─────────────────────────────────────────────
INSERT INTO public.achievements (key,name,description,icon,xp_reward,rarity,category) VALUES
('first_workout','First Blood','Complete your first workout','⚡',50,'common','milestone'),
('workouts_10','Getting Serious','Complete 10 workouts','💪',100,'common','milestone'),
('workouts_50','Dedicated','Complete 50 workouts','🏋️',300,'rare','milestone'),
('workouts_100','Century','Complete 100 workouts','🔥',750,'epic','milestone'),
('workouts_365','Year of Iron','Complete 365 workouts','👑',5000,'legendary','milestone'),
('sets_100','Century of Sets','Log 100 sets total','💯',100,'common','milestone'),
('sets_1000','Iron Volume','1,000 sets logged','⚙️',500,'rare','milestone'),
('sets_10000','The Grind Never Stops','10,000 sets logged','🌋',3000,'legendary','milestone'),
('streak_3','Warming Up','3-day workout streak','🌡️',30,'common','consistency'),
('streak_7','Week Warrior','7-day streak','🗓️',100,'common','consistency'),
('streak_30','Monthly Iron','30-day streak','📅',500,'rare','consistency'),
('streak_100','Unstoppable','100-day streak','🚀',2000,'epic','consistency'),
('streak_365','Legend','365-day streak','🏆',10000,'legendary','consistency'),
('first_pr','New Ground','Set your first personal record','🎯',100,'common','strength'),
('prs_10','Record Breaker','Set 10 personal records','📈',300,'rare','strength'),
('prs_50','Perpetual Progress','Set 50 personal records','🏅',1000,'epic','strength'),
('bench_1x_bw','Push It','Bench press your bodyweight','💪',250,'rare','strength'),
('bench_1_5x_bw','Chest Day Legend','Bench 1.5× your bodyweight','🦅',500,'epic','strength'),
('squat_1_5x_bw','Legs Day Hero','Squat 1.5× your bodyweight','🦵',500,'epic','strength'),
('deadlift_2x_bw','From the Floor','Deadlift 2× your bodyweight','⬆️',500,'epic','strength'),
('total_5x_bw','Powerhouse','S+B+D total over 5× bodyweight','🌟',2000,'legendary','strength'),
('level_iron','Iron Forged','Reach Iron level','⚙️',200,'common','strength'),
('level_bronze','Bronze Warrior','Reach Bronze level','🥉',500,'rare','strength'),
('level_silver','Silver Standard','Reach Silver level','🥈',1000,'rare','strength'),
('level_gold','Gold Standard','Reach Gold level','🥇',2000,'epic','strength'),
('level_platinum','Platinum Athlete','Reach Platinum level','💎',5000,'legendary','strength'),
('level_elite','Elite','Reach Elite level — top 1%','👑',10000,'legendary','strength'),
('first_friend','Training Partner','Add your first friend','🤝',50,'common','social'),
('friends_5','Squad','Have 5 friends on PlateTrack','👥',150,'common','social'),
('challenge_won','Challenger','Win a challenge','🏆',300,'rare','social'),
('nutrition_streak_7','Fuel the Machine','7 days of nutrition logging','🥗',150,'common','nutrition'),
('nutrition_streak_30','Dialed In','30 consecutive nutrition logs','🎯',500,'rare','nutrition')
ON CONFLICT (key) DO NOTHING;

-- ── REWARD CATALOG ────────────────────────────────────────────
INSERT INTO public.reward_catalog (name,description,xp_cost,reward_type,reward_value,icon) VALUES
('7-Day Pro Trial','Unlock Pro for 7 days — no card required',5000,'pro_trial_7','{"days":7}','⚡'),
('1-Month Pro Trial','Full Pro access for 30 days',15000,'pro_trial_30','{"days":30}','🚀'),
('3-Month Pro Trial','90 days of full Pro access',30000,'pro_trial_90','{"days":90}','🔥'),
('Custom Plate Colours','Unlock custom barbell plate colours in-app',8000,'cosmetic','{"feature":"custom_plates"}','🎨'),
('Challenge Slot','Create an extra challenge this month',6000,'challenge_slot',null,'🏆'),
('10% Off Pro Annual','Discount code for your next annual upgrade',20000,'discount_code','{"pct":10}','🎫'),
('30% Off Pro Annual','Biggest discount — for dedicated athletes only',35000,'discount_code','{"pct":30}','👑')
ON CONFLICT DO NOTHING;

-- ── EXERCISES (120+) ──────────────────────────────────────────
INSERT INTO public.exercises (name,slug,category,tracking_type,primary_muscles,equipment,is_default) VALUES
-- Barbell
('Back Squat','back-squat','barbell','weight_reps',ARRAY['quads','glutes'],'barbell',true),
('Front Squat','front-squat','barbell','weight_reps',ARRAY['quads','core'],'barbell',true),
('Bench Press','bench-press','barbell','weight_reps',ARRAY['chest','triceps'],'barbell',true),
('Incline Bench Press','incline-bench-press','barbell','weight_reps',ARRAY['upper_chest'],'barbell',true),
('Deadlift','deadlift','barbell','weight_reps',ARRAY['hamstrings','glutes','back'],'barbell',true),
('Romanian Deadlift','romanian-deadlift','barbell','weight_reps',ARRAY['hamstrings','glutes'],'barbell',true),
('Overhead Press','overhead-press','barbell','weight_reps',ARRAY['shoulders','triceps'],'barbell',true),
('Barbell Row','barbell-row','barbell','weight_reps',ARRAY['lats','rhomboids'],'barbell',true),
('Hip Thrust','hip-thrust','barbell','weight_reps',ARRAY['glutes'],'barbell',true),
('Power Clean','power-clean','barbell','weight_reps',ARRAY['full_body'],'barbell',true),
('Sumo Deadlift','sumo-deadlift','barbell','weight_reps',ARRAY['glutes','hamstrings'],'barbell',true),
('Close Grip Bench Press','close-grip-bench','barbell','weight_reps',ARRAY['triceps','chest'],'barbell',true),
('Good Morning','good-morning','barbell','weight_reps',ARRAY['hamstrings','lower_back'],'barbell',true),
('Zercher Squat','zercher-squat','barbell','weight_reps',ARRAY['quads','core'],'barbell',true),
('Hang Clean','hang-clean','barbell','weight_reps',ARRAY['full_body'],'barbell',true),
-- Dumbbell
('Dumbbell Press','db-press','dumbbell','weight_reps',ARRAY['chest','triceps'],'dumbbells',true),
('Dumbbell Row','db-row','dumbbell','weight_reps',ARRAY['lats','biceps'],'dumbbells',true),
('Dumbbell Curl','db-curl','dumbbell','weight_reps',ARRAY['biceps'],'dumbbells',true),
('Lateral Raise','lateral-raise','dumbbell','weight_reps',ARRAY['lateral_deltoid'],'dumbbells',true),
('Dumbbell Shoulder Press','db-shoulder-press','dumbbell','weight_reps',ARRAY['shoulders'],'dumbbells',true),
('Dumbbell Lunge','db-lunge','dumbbell','weight_reps',ARRAY['quads','glutes'],'dumbbells',true),
('Dumbbell Romanian Deadlift','db-rdl','dumbbell','weight_reps',ARRAY['hamstrings'],'dumbbells',true),
('Dumbbell Fly','db-fly','dumbbell','weight_reps',ARRAY['chest'],'dumbbells',true),
('Hammer Curl','hammer-curl','dumbbell','weight_reps',ARRAY['biceps','brachialis'],'dumbbells',true),
('Tricep Kickback','tricep-kickback','dumbbell','weight_reps',ARRAY['triceps'],'dumbbells',true),
('Dumbbell Shrug','db-shrug','dumbbell','weight_reps',ARRAY['traps'],'dumbbells',true),
('Goblet Squat','goblet-squat','dumbbell','weight_reps',ARRAY['quads','core'],'dumbbells',true),
('Dumbbell Step Up','db-step-up','dumbbell','weight_reps',ARRAY['quads','glutes'],'dumbbells',true),
('Arnold Press','arnold-press','dumbbell','weight_reps',ARRAY['shoulders'],'dumbbells',true),
('Dumbbell Pullover','db-pullover','dumbbell','weight_reps',ARRAY['lats','chest'],'dumbbells',true),
-- Bodyweight
('Push-Up','push-up','bodyweight','bodyweight_reps',ARRAY['chest','triceps'],'none',true),
('Pull-Up','pull-up','bodyweight','bodyweight_reps',ARRAY['lats','biceps'],'pull_up_bar',true),
('Chin-Up','chin-up','bodyweight','bodyweight_reps',ARRAY['biceps','lats'],'pull_up_bar',true),
('Dip','dip','bodyweight','bodyweight_reps',ARRAY['triceps','chest'],'dip_bar',true),
('Bodyweight Squat','bw-squat','bodyweight','bodyweight_reps',ARRAY['quads','glutes'],'none',true),
('Lunge','lunge','bodyweight','bodyweight_reps',ARRAY['quads','glutes'],'none',true),
('Burpee','burpee','bodyweight','bodyweight_reps',ARRAY['full_body'],'none',true),
('Mountain Climber','mountain-climber','bodyweight','bodyweight_reps',ARRAY['core','shoulders'],'none',true),
('Jumping Jack','jumping-jack','bodyweight','bodyweight_reps',ARRAY['full_body'],'none',true),
('Box Jump','box-jump','bodyweight','bodyweight_reps',ARRAY['quads','glutes'],'box',true),
('Pistol Squat','pistol-squat','bodyweight','bodyweight_reps',ARRAY['quads','balance'],'none',true),
('Muscle Up','muscle-up','bodyweight','bodyweight_reps',ARRAY['lats','chest','triceps'],'pull_up_bar',true),
('Plank','plank','bodyweight','timed',ARRAY['core'],'none',true),
('Side Plank','side-plank','bodyweight','timed',ARRAY['obliques'],'none',true),
('Hollow Hold','hollow-hold','bodyweight','timed',ARRAY['core'],'none',true),
('L-Sit','l-sit','bodyweight','timed',ARRAY['core','hip_flexors'],'none',true),
('Wall Sit','wall-sit','bodyweight','timed',ARRAY['quads'],'none',true),
('Dead Hang','dead-hang','bodyweight','timed',ARRAY['forearms','lats'],'pull_up_bar',true),
('Superman Hold','superman-hold','bodyweight','timed',ARRAY['lower_back','glutes'],'none',true),
('Bear Crawl','bear-crawl','bodyweight','distance_time',ARRAY['full_body'],'none',true),
-- Machine / Cable
('Lat Pulldown','lat-pulldown','machine','weight_reps',ARRAY['lats','biceps'],'cable',true),
('Cable Row','cable-row','machine','weight_reps',ARRAY['lats','rhomboids'],'cable',true),
('Leg Press','leg-press','machine','weight_reps',ARRAY['quads','glutes'],'machine',true),
('Leg Extension','leg-extension','machine','weight_reps',ARRAY['quads'],'machine',true),
('Leg Curl','leg-curl','machine','weight_reps',ARRAY['hamstrings'],'machine',true),
('Cable Fly','cable-fly','machine','weight_reps',ARRAY['chest'],'cable',true),
('Tricep Pushdown','tricep-pushdown','machine','weight_reps',ARRAY['triceps'],'cable',true),
('Face Pull','face-pull','machine','weight_reps',ARRAY['rear_deltoid','rhomboids'],'cable',true),
('Cable Curl','cable-curl','machine','weight_reps',ARRAY['biceps'],'cable',true),
('Chest Press Machine','chest-press-machine','machine','weight_reps',ARRAY['chest'],'machine',true),
('Shoulder Press Machine','shoulder-press-machine','machine','weight_reps',ARRAY['shoulders'],'machine',true),
('Assisted Pull-Up','assisted-pull-up','machine','weight_reps',ARRAY['lats','biceps'],'machine',true),
('Smith Machine Squat','smith-squat','machine','weight_reps',ARRAY['quads','glutes'],'smith_machine',true),
('Hip Abductor Machine','hip-abductor','machine','weight_reps',ARRAY['glutes','abductors'],'machine',true),
('Calf Raise Machine','calf-raise-machine','machine','weight_reps',ARRAY['calves'],'machine',true),
-- Cardio
('Running','running','cardio','distance_time',ARRAY['legs','cardiovascular'],'none',true),
('Cycling','cycling','cardio','distance_time',ARRAY['legs','cardiovascular'],'bike',true),
('Rowing','rowing','cardio','distance_time',ARRAY['full_body','cardiovascular'],'rower',true),
('Swimming','swimming','cardio','distance_time',ARRAY['full_body'],'pool',true),
('Jump Rope','jump-rope','cardio','timed',ARRAY['calves','cardiovascular'],'jump_rope',true),
('Elliptical','elliptical','cardio','distance_time',ARRAY['full_body'],'elliptical',true),
('Stair Climber','stair-climber','cardio','timed',ARRAY['legs','cardiovascular'],'stair_climber',true),
('Walking','walking','cardio','distance_time',ARRAY['legs'],'none',true),
('Assault Bike','assault-bike','cardio','distance_time',ARRAY['full_body'],'assault_bike',true),
('Ski Erg','ski-erg','cardio','distance_time',ARRAY['full_body'],'ski_erg',true),
-- Olympic / CrossFit
('Clean and Jerk','clean-and-jerk','olympic','weight_reps',ARRAY['full_body'],'barbell',true),
('Snatch','snatch','olympic','weight_reps',ARRAY['full_body'],'barbell',true),
('Turkish Get-Up','turkish-get-up','functional','weight_reps',ARRAY['full_body'],'kettlebell',true),
('Kettlebell Swing','kb-swing','functional','weight_reps',ARRAY['glutes','hamstrings'],'kettlebell',true),
('Thruster','thruster','functional','weight_reps',ARRAY['full_body'],'barbell',true),
('Wall Ball','wall-ball','functional','weight_reps',ARRAY['full_body'],'medicine_ball',true),
('Box Step-Over','box-step-over','functional','bodyweight_reps',ARRAY['quads','glutes'],'box',true),
('Farmer Carry','farmer-carry','functional','distance_time',ARRAY['forearms','traps','core'],'dumbbells',true),
('Sled Push','sled-push','functional','distance_time',ARRAY['full_body'],'sled',true),
('Battle Ropes','battle-ropes','functional','timed',ARRAY['shoulders','core'],'battle_ropes',true)
ON CONFLICT (slug) DO NOTHING;
