-- PlateTrack Exercise Seed Data — run after 01_main.sql
-- 120+ exercises across all categories

INSERT INTO public.exercises (name, slug, category, primary_muscles, secondary_muscles, tracking_type, is_default) VALUES
-- BARBELL (15)
('Back Squat','back-squat','barbell','{"Quadriceps","Glutes"}','{"Hamstrings","Core"}','weight_reps',true),
('Front Squat','front-squat','barbell','{"Quadriceps"}','{"Glutes","Core"}','weight_reps',true),
('Bench Press','bench-press','barbell','{"Pectoralis Major"}','{"Anterior Deltoid","Triceps"}','weight_reps',true),
('Incline Bench Press','incline-bench-press','barbell','{"Upper Pectoralis"}','{"Anterior Deltoid","Triceps"}','weight_reps',true),
('Deadlift','deadlift','barbell','{"Hamstrings","Glutes","Erector Spinae"}','{"Quadriceps","Lats","Traps"}','weight_reps',true),
('Romanian Deadlift','romanian-deadlift','barbell','{"Hamstrings","Glutes"}','{"Erector Spinae","Lats"}','weight_reps',true),
('Barbell Row','barbell-row','barbell','{"Lats","Rhomboids"}','{"Biceps","Rear Deltoid"}','weight_reps',true),
('Overhead Press','overhead-press','barbell','{"Anterior Deltoid","Lateral Deltoid"}','{"Triceps","Upper Chest"}','weight_reps',true),
('Push Press','push-press','barbell','{"Anterior Deltoid"}','{"Triceps","Legs"}','weight_reps',true),
('Good Morning','good-morning','barbell','{"Hamstrings","Erector Spinae"}','{"Glutes"}','weight_reps',true),
('Barbell Curl','barbell-curl','barbell','{"Biceps Brachii"}','{"Brachialis","Brachioradialis"}','weight_reps',true),
('Close-Grip Bench','close-grip-bench','barbell','{"Triceps Brachii"}','{"Pectoralis Minor","Anterior Deltoid"}','weight_reps',true),
('Hip Thrust (Barbell)','hip-thrust-barbell','barbell','{"Glutes"}','{"Hamstrings","Core"}','weight_reps',true),
('Pendlay Row','pendlay-row','barbell','{"Lats","Rhomboids","Traps"}','{"Biceps","Rear Deltoid"}','weight_reps',true),
('Zercher Squat','zercher-squat','barbell','{"Quadriceps","Glutes"}','{"Core","Upper Back"}','weight_reps',true),
-- DUMBBELL (15)
('Dumbbell Press','dumbbell-press','dumbbell','{"Pectoralis Major"}','{"Anterior Deltoid","Triceps"}','weight_reps',true),
('Incline Dumbbell Press','incline-dumbbell-press','dumbbell','{"Upper Pectoralis"}','{"Anterior Deltoid","Triceps"}','weight_reps',true),
('Dumbbell Row','dumbbell-row','dumbbell','{"Lats"}','{"Biceps","Rhomboids"}','weight_reps',true),
('Dumbbell Shoulder Press','dumbbell-shoulder-press','dumbbell','{"Anterior Deltoid","Lateral Deltoid"}','{"Triceps"}','weight_reps',true),
('Lateral Raise','lateral-raise','dumbbell','{"Lateral Deltoid"}','{"Anterior Deltoid"}','weight_reps',true),
('Dumbbell Curl','dumbbell-curl','dumbbell','{"Biceps Brachii"}','{"Brachialis"}','weight_reps',true),
('Hammer Curl','hammer-curl','dumbbell','{"Brachioradialis","Brachialis"}','{"Biceps Brachii"}','weight_reps',true),
('Dumbbell Tricep Extension','dumbbell-tricep-extension','dumbbell','{"Triceps Brachii"}','{}','weight_reps',true),
('Dumbbell Fly','dumbbell-fly','dumbbell','{"Pectoralis Major"}','{"Anterior Deltoid"}','weight_reps',true),
('Romanian Deadlift (DB)','rdl-dumbbell','dumbbell','{"Hamstrings","Glutes"}','{"Erector Spinae"}','weight_reps',true),
('Goblet Squat','goblet-squat','dumbbell','{"Quadriceps","Glutes"}','{"Core"}','weight_reps',true),
('Dumbbell Lunge','dumbbell-lunge','dumbbell','{"Quadriceps","Glutes"}','{"Hamstrings"}','weight_reps',true),
('Rear Delt Fly','rear-delt-fly','dumbbell','{"Posterior Deltoid","Rhomboids"}','{}','weight_reps',true),
('Dumbbell Shrug','dumbbell-shrug','dumbbell','{"Trapezius"}','{}','weight_reps',true),
('Dumbbell Split Squat','dumbbell-split-squat','dumbbell','{"Quadriceps","Glutes"}','{"Hamstrings"}','weight_reps',true),
-- MACHINE/CABLE (15)
('Lat Pulldown','lat-pulldown','machine','{"Latissimus Dorsi"}','{"Biceps","Rear Deltoid"}','weight_reps',true),
('Seated Cable Row','seated-cable-row','machine','{"Lats","Rhomboids"}','{"Biceps"}','weight_reps',true),
('Cable Fly','cable-fly','machine','{"Pectoralis Major"}','{"Anterior Deltoid"}','weight_reps',true),
('Leg Press','leg-press','machine','{"Quadriceps","Glutes"}','{"Hamstrings"}','weight_reps',true),
('Leg Curl','leg-curl','machine','{"Hamstrings"}','{"Glutes"}','weight_reps',true),
('Leg Extension','leg-extension','machine','{"Quadriceps"}','{}','weight_reps',true),
('Cable Tricep Pushdown','cable-tricep-pushdown','machine','{"Triceps Brachii"}','{}','weight_reps',true),
('Cable Curl','cable-curl','machine','{"Biceps Brachii"}','{}','weight_reps',true),
('Chest Press Machine','chest-press-machine','machine','{"Pectoralis Major"}','{"Anterior Deltoid","Triceps"}','weight_reps',true),
('Shoulder Press Machine','shoulder-press-machine','machine','{"Deltoids"}','{"Triceps"}','weight_reps',true),
('Pec Deck','pec-deck','machine','{"Pectoralis Major"}','{"Anterior Deltoid"}','weight_reps',true),
('Hip Abductor','hip-abductor','machine','{"Gluteus Medius"}','{}','weight_reps',true),
('Calf Raise Machine','calf-raise-machine','machine','{"Gastrocnemius","Soleus"}','{}','weight_reps',true),
('Assisted Pull-Up','assisted-pull-up','machine','{"Lats","Biceps"}','{}','weight_reps',true),
('Smith Machine Squat','smith-machine-squat','machine','{"Quadriceps","Glutes"}','{"Hamstrings"}','weight_reps',true),
-- BODYWEIGHT (20)
('Pull-Up','pull-up','bodyweight','{"Latissimus Dorsi","Biceps"}','{"Rear Deltoid"}','bodyweight_reps',true),
('Chin-Up','chin-up','bodyweight','{"Biceps Brachii","Lats"}','{}','bodyweight_reps',true),
('Push-Up','push-up','bodyweight','{"Pectoralis Major"}','{"Triceps","Anterior Deltoid"}','bodyweight_reps',true),
('Dip','dip','bodyweight','{"Triceps","Pectoralis Minor"}','{"Anterior Deltoid"}','bodyweight_reps',true),
('Squat','squat','bodyweight','{"Quadriceps","Glutes"}','{"Hamstrings"}','bodyweight_reps',true),
('Lunge','lunge','bodyweight','{"Quadriceps","Glutes"}','{"Hamstrings"}','bodyweight_reps',true),
('Glute Bridge','glute-bridge','bodyweight','{"Glutes","Hamstrings"}','{"Core"}','bodyweight_reps',true),
('Plank','plank','bodyweight','{"Core","Transverse Abdominis"}','{"Shoulders"}','timed',true),
('Side Plank','side-plank','bodyweight','{"Obliques","Core"}','{}','timed',true),
('Hollow Hold','hollow-hold','bodyweight','{"Core"}','{}','timed',true),
('Hanging Knee Raise','hanging-knee-raise','bodyweight','{"Hip Flexors","Rectus Abdominis"}','{}','bodyweight_reps',true),
('Toes to Bar','toes-to-bar','bodyweight','{"Rectus Abdominis","Hip Flexors"}','{}','bodyweight_reps',true),
('Inverted Row','inverted-row','bodyweight','{"Lats","Rhomboids"}','{"Biceps"}','bodyweight_reps',true),
('Pistol Squat','pistol-squat','bodyweight','{"Quadriceps"}','{"Glutes","Core"}','bodyweight_reps',true),
('Nordic Curl','nordic-curl','bodyweight','{"Hamstrings"}','{}','bodyweight_reps',true),
('Diamond Push-Up','diamond-push-up','bodyweight','{"Triceps Brachii"}','{"Pectoralis Minor"}','bodyweight_reps',true),
('Wide-Grip Push-Up','wide-grip-push-up','bodyweight','{"Pectoralis Major"}','{"Anterior Deltoid"}','bodyweight_reps',true),
('Calf Raise (BW)','calf-raise-bw','bodyweight','{"Gastrocnemius","Soleus"}','{}','bodyweight_reps',true),
('Step Up','step-up','bodyweight','{"Quadriceps","Glutes"}','{"Hamstrings"}','bodyweight_reps',true),
('Good Morning (BW)','good-morning-bw','bodyweight','{"Hamstrings","Erector Spinae"}','{}','bodyweight_reps',true),
-- WEIGHTED BODYWEIGHT (5)
('Weighted Pull-Up','weighted-pull-up','bodyweight','{"Latissimus Dorsi","Biceps"}','{}','weighted_bodyweight',true),
('Weighted Dip','weighted-dip','bodyweight','{"Triceps","Pectoralis Minor"}','{}','weighted_bodyweight',true),
('Weighted Push-Up','weighted-push-up','bodyweight','{"Pectoralis Major"}','{"Triceps"}','weighted_bodyweight',true),
('Weighted Squat','weighted-squat','bodyweight','{"Quadriceps","Glutes"}','{}','weighted_bodyweight',true),
('Weighted Lunge','weighted-lunge','bodyweight','{"Quadriceps","Glutes"}','{}','weighted_bodyweight',true),
-- CARDIO/DISTANCE (12)
('Running','running','cardio','{"Quadriceps","Hamstrings","Glutes","Calves"}','{"Core"}','distance_time',true),
('Cycling','cycling','cardio','{"Quadriceps","Hamstrings","Glutes"}','{"Calves"}','distance_time',true),
('Rowing','rowing','cardio','{"Lats","Rhomboids","Hamstrings","Glutes"}','{"Biceps","Core"}','distance_time',true),
('Swimming','swimming','cardio','{"Full Body"}','{}','distance_time',true),
('Jump Rope','jump-rope','cardio','{"Calves","Shoulders"}','{"Core"}','timed',true),
('Stair Climber','stair-climber','cardio','{"Quadriceps","Glutes","Calves"}','{}','timed',true),
('Elliptical','elliptical','cardio','{"Full Body"}','{}','timed',true),
('Walking','walking','cardio','{"Quadriceps","Calves"}','{}','distance_time',true),
('Sprint','sprint','cardio','{"Quadriceps","Hamstrings","Glutes"}','{}','distance_time',true),
('Assault Bike','assault-bike','cardio','{"Full Body"}','{}','timed',true),
('SkiErg','skierg','cardio','{"Lats","Core","Triceps"}','{}','distance_time',true),
('Sled Push','sled-push','cardio','{"Quadriceps","Glutes","Core"}','{}','distance_time',true),
-- OLYMPIC/FUNCTIONAL (10)
('Clean and Jerk','clean-and-jerk','olympic','{"Full Body"}','{}','weight_reps',true),
('Snatch','snatch','olympic','{"Full Body"}','{}','weight_reps',true),
('Power Clean','power-clean','olympic','{"Hamstrings","Glutes","Traps"}','{}','weight_reps',true),
('Hang Clean','hang-clean','olympic','{"Hamstrings","Glutes"}','{}','weight_reps',true),
('Kettlebell Swing','kettlebell-swing','functional','{"Glutes","Hamstrings","Core"}','{"Shoulders"}','weight_reps',true),
('Kettlebell Turkish Get-Up','turkish-get-up','functional','{"Core","Shoulders","Glutes"}','{}','weight_reps',true),
('Box Jump','box-jump','functional','{"Quadriceps","Glutes","Calves"}','{}','bodyweight_reps',true),
('Burpee','burpee','functional','{"Full Body"}','{}','bodyweight_reps',true),
('Wall Ball','wall-ball','functional','{"Quadriceps","Shoulders"}','{"Core"}','weight_reps',true),
('Thruster','thruster','functional','{"Quadriceps","Shoulders","Glutes"}','{"Triceps"}','weight_reps',true),
-- FLEXIBILITY/YOGA (6)
('Hip Flexor Stretch','hip-flexor-stretch','flexibility','{"Hip Flexors"}','{}','timed',true),
('Hamstring Stretch','hamstring-stretch','flexibility','{"Hamstrings"}','{}','timed',true),
('Pigeon Pose','pigeon-pose','flexibility','{"Glutes","Hip Flexors"}','{}','timed',true),
('Thoracic Rotation','thoracic-rotation','flexibility','{"Thoracic Spine","Obliques"}','{}','timed',true),
('Child Pose','child-pose','flexibility','{"Lats","Erector Spinae"}','{}','timed',true),
('Cat-Cow','cat-cow','flexibility','{"Erector Spinae","Core"}','{}','bodyweight_reps',true)
ON CONFLICT (slug) DO NOTHING;
